

<?php include("navbar.phtml") ?>

<br><br>

<section class="section">
	<div class="p-4 rounded-3 m-auto bg-light container-consumption" style="width: 90%">

		<h1 class="text-center">
			Consumo
		</h1>
		<p>
			Nulla facilisi. Nam cursus maximus commodo. Curabitur posuere augue sit amet enim imperdiet scelerisque. In sit amet nibh eu turpis viverra dignissim quis eu leo. Sed ac dictum augue. Vestibulum sit amet enim vel odio maximus bibendum. Nullam porttitor tristique quam, ac pharetra enim gravida molestie. Vestibulum vel mattis arcu, tristique ultrices enim.
		</p>

		<div class="consumption-for-month bg-gray p-4 rounded-3">
			<h4>Consumo p/mês</h4>
			<p>
				Vivamus venenatis est at mi dapibus posuere. Nam ac nisl sed sapien rutrum sollicitudin id quis sapien. Integer malesuada euismod auctor. Phasellus rhoncus tortor ut turpis dignissim, quis mollis nibh scelerisque. Suspendisse at porta ante, sit amet porttitor enim. Cras metus erat, finibus ele
			</p> 
			<div class="bg-white p-4 rounded-3" style="overflow-x: scroll; overflow-y: scroll">

				<button class="btn btn-success btn-see-more" style="float: right; min-width: 110px">Ver Mais + 
				</button>

				<button class="btn btn-success btn-see-less d-none" style="float: right; min-width: 110px">Ver Menos - 
				</button>

				<p class="text-green"><b>Lorem Ipsum</b></p>
				<br>
				<table class="text-center m-auto" style="color: black; width: 90%">
					<tr class="tr-3">
						<td class="tr-1" style="border-bottom: 1px solid white">
							<b>Mês</b>
						</td>
						<td>jan/19</td>
						<td>fev/19</td>
						<td>mar/19</td>
						<td>abr/19</td>
						<td>jun/19</td>
						<td>...</td>
						<td class="tr-1" style="border-bottom: 1px solid white">
							<b>Total</b>
						</td>
					</tr>
					<tr class="bg-light">
						<td class="tr-1" style="border-bottom: 1px solid white">
							<b>FP</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="tr-1" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
					<tr class="tr-3">
						<td class="tr-1" style="border-bottom: 1px solid white">
							<b>P</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="tr-1" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
					<tr class="bg-light">
						<td class="tr-1" style="border-bottom: 1px solid white">
							<b>Total</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="tr-1" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
				</table>
				<br>
				<div class="tables-more d-none">
					<table class="text-center table-animate m-auto" style="color: black; width: 90%">
						<tr class="tr-1">
							<td>
								Nome
							</td>
							<td>jan/19</td>
							<td>fev/19</td>
							<td>mar/19</td>
							<td>abr/19</td>
							<td>jun/19</td>
							<td>...</td>
							<td>Total</td>
							<td>
								Opções
							</td>
						</tr>
						<tr class="tr-3 tr-cons-ponta">
							<td class="text-start">Lorem Ipsum</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>000,0</td>
							<td>
								<i class="fa-solid fa-pen edit-line text-dark" title="Editar"></i>
								<i class="fa-solid fa-floppy-disk ms-2 save-line-disabled" title="Salvar" style="color: lightgray"></i>
								<i class="fa-solid fa-floppy-disk text-success ms-2 d-none save-line" title="Salvar"></i>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="text-start">Lorem Ipsum</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td></td>
						</tr>
						<tr class="tr-3 tr-cons-fp">
							<td class="text-start">Lorem Ipsum</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>000,0</td>
							<td>
								<i class="fa-solid fa-pen edit-line text-dark" title="Editar" ></i>
								<i class="fa-solid fa-floppy-disk ms-2 save-line-disabled" title="Salvar" style="color: lightgray"></i>
								<i class="fa-solid fa-floppy-disk text-success ms-2 d-none save-line" title="Salvar"></i>
							</td>

						</tr>
						<tr class="bg-light">
							<td class="text-start">Lorem Ipsum elementum maur</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td></td>
						</tr>
						<tr class="tr-3">
							<td class="text-start">M malesuada sem</td>
							<td>00,00</td>
							<td>00,00</td>
							<td>00,00</td>
							<td>00,00</td>
							<td>00,00</td>
							<td>00,00</td>
							<td>00,00</td>
							<td></td>
						</tr>
						<tr class="bg-light">
							<td class="text-start">Maecenas vel te</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td>0,0%</td>
							<td></td>
						</tr>
					</table>
					<br>
					<table class="text-center table-animate m-auto" style="color: black; width: 90%">
						<tr class="tr-1">
							<td>
								Nome
							</td>
							<td>jan/19</td>
							<td>fev/19</td>
							<td>mar/19</td>
							<td>abr/19</td>
							<td>jun/19</td>
							<td>...</td>
							<td>Máx.</td>
							<td>Méd.</td>
							<td>
								Opções
							</td>
						</tr>

						<tr class="tr-3">
							<td>
								Nulla facilisi. Nam 
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>000,0</td>
							<td>000,0</td>
							<td>
								<i class="fa-solid fa-pen edit-line text-dark" title="Editar"></i>
								<i class="fa-solid fa-floppy-disk ms-2 save-line-disabled" title="Salvar" style="color: lightgray"></i>
								<i class="fa-solid fa-floppy-disk text-success ms-2 d-none save-line" title="Salvar"></i>
							</td>
						</tr>

						<tr class="bg-light">
							<td>
								ABC
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>
								<input type="text" name="" value="000,00" disabled>
							</td>
							<td>000,0</td>
							<td>000,0</td>
							<td>
								<i class="fa-solid fa-pen edit-line text-dark" title="Editar"></i>
								<i class="fa-solid fa-floppy-disk ms-2 save-line-disabled" title="Salvar" style="color: lightgray"></i>
								<i class="fa-solid fa-floppy-disk text-success ms-2 d-none save-line" title="Salvar"></i>
							</td>
						</tr>
						
					</table>
				</div>
			</div>
			<br>
			<div class="bg-white p-4 rounded-3">
				<p class="text-green"><b>Gráfico</b></p>
				<br>
				<img src="img/img.png" class="graph-1 w-50">
				<br>
				<img src="img/img.png" class="graph-2 w-50">

			</div>
		</div>
	
	</div>
</section>

<script>
	$(window).on("scroll load7",function(){
		var aparecer = 50; 
		var eleHeight = $('.graph-1').outerHeight(); 
		var eleTopo = $('.graph-1').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".graph-1").css("animation", "fade 3s 1")
			$(".graph-1").css("-webkit-animation-fill-mode", "forwards")
		}
	})

	$(window).on("scroll load8",function(){
		var aparecer = 50; 
		var eleHeight = $('.graph-2').outerHeight(); 
		var eleTopo = $('.graph-2').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".graph-2").css("animation", "fade 3s 1")
			$(".graph-2").css("-webkit-animation-fill-mode", "forwards")
		}
	})
</script>