
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand ms-1" href="#" style="margin-right: 40%">
    	<img src="img/logo6.png" style="width: 200px">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 row">
        <li class="nav-item col">
          <a class="nav-link" aria-current="page" href="#">Contato</a>
        </li>
        <li class="nav-item col">
          <a class="nav-link" aria-current="page" href="#suporte">Suporte</a>
        </li>
       	<li class="nav-item col">
          <a class="nav-link login-link p-2 ps-3 pe-3" href="#">Entrar</a>
        </li>

        <li class="nav-item col">
          <a class="nav-link" href="#">
          	<img src="img/dna_trans.png" style="width: 50px">
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!--<hr style="margin-top: -3px">-->

<div class="container-login text-center p-3">
	<i class="fa-solid fa-xmark text-danger" style="margin-left: 50%; cursor: pointer"></i>
	<h1 class="text-success">LOG IN</h1>
	<br>
	<input type="text" name="" placeholder="Email">
	<br><br>
	<input type="password" name="" placeholder="Senha">
	<br><br>
	<img class="off-img" src="img/off.jpg" style="width: 30px; cursor: pointer"/>
	<img class="on-img d-none" src="img/on.jpg" style="width: 30px; cursor: pointer"/> Permanecer Logado
	<br><br>
	<button class="text-white btn btn-success"><i class="fa-solid fa-right-to-bracket"></i> Entrar</button>
</div>

<div class="parallax parallaxTemplate1"></div>

<div class="text-center p-5 rounded-2 bg-white bemvindo" style="opacity: 0">
	<h1 class="text-success">SEJA BEM-VINDO</h1>
	<br>
		<p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tortor erat, condimentum at enim hendrerit, fermentum faucibus ex. Phasellus ut nisi ac diam consectetur rhoncus. Proin molestie ex ut feugiat sodales. Nulla nisl ipsum, commodo a eros vel, dignissim tincidunt ex. Morbi et velit vel tortor faucibus aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc ut eleifend nisi. Nullam porttitor, elit non fermentum consectetur, dui risus dictum metus, nec fermentum odio erat eu enim. Suspendisse eu urna nunc. Suspendisse sodales cursus risus a vehicula. Suspendisse potenti.</p>
</div>

<div class="parallax parallaxTemplate2"></div>


<div class="text-center p-5 rounded-2">
		<div class="row row-vantages">
			<div class="col col-sus ">
				<h3>Sustentabilidade</h3>
				<br><br>
				<i class="i-v fa-solid fa-earth-americas text-success text-center m-auto mt-2" style="font-size: 10em"></i>
			</div>
			<div class="col col-tech">
				<h3>Tecnologia</h3>
				<br><br>
				<i class="i-v fa-solid fa-chalkboard text-success text-center m-auto mt-2" style="font-size: 10em"></i>
			</div>
			<div class="col col-eco">
				<h3>Economia</h3>
				<br><br>
				<i class="i-v fa-solid fa-hand-holding-dollar text-success text-center m-auto mt-2" style="font-size: 10em"></i>
			</div>
		</div>
		<button class="btn btn-success btn-ver-sistema">Ver Sistema</button>
</div>

<div class="parallax parallaxTemplate3"></div>

<div class="text-center bg-white p-5 rounded-2 row supporte">
	<h1 class="text-success mb-4">SUPORTE</h1>
	<div class="col text-center">
		<i class="fa-solid fa-envelope-open-text text-success text-center m-auto mt-2" style="font-size: 13em"></i>
	</div>

	<div class="col suporte-div">
		<form id="suporte" class="form-contact add-indexes">
			<input type="text" name="" placeholder="Nome" class="rounded-pill bg-light">
			<br><br>
			<input type="text" name="" placeholder="Email" class="rounded-pill bg-light">
			<br><br>
			<input type="text" name="" placeholder="Título" class="rounded-pill bg-light">
			<br><br>
			<textarea placeholder="Mensagem" class="rounded-pill p-2 bg-light"></textarea>
			<br><br>
			<button class="btn btn-success w-25 rounded-pill btn-send-support"><span class="span-send">Enviar</span><span class="icon-send text-white d-none"><i class="fa-solid fa-paper-plane"></i></span></button>
		</form>
	</div>
</div>

<footer class="bg-light text-center p-2">
	<p>@2021 GELD | <a href="">Termos</a> | <a href="">Política de Privacidade</a></p>
</footer>