<?php include("navbar.phtml") ?>


<br><br>

<section class="section section-intro">
	<div class="text-center p-4 rounded-3 m-auto bg-light" style="width: 90%">
	<h1 class="">
		Introdução
	</h1>
	<br>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sem elit, eleifend ac ullamcorper in, egestas nec nunc. Aenean quis tempus lorem. Nullam at sodales ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis a rutrum libero. Ut arcu elit, hendrerit quis posuere quis, efficitur et odio. Vestibulum odio lacus, malesuada nec vehicula quis, posuere nec justo. Etiam in eros arcu. Proin at sem massa. Nullam eget ante feugiat, dignissim enim quis, elementum augue. Vestibulum in aliquam enim. Aenean dolor nibh, euismod id massa eget, convallis cursus sem. Nunc ullamcorper enim a nunc porta finibus. Ut quis ornare nibh. Maecenas iaculis lacus at dolor venenatis suscipit.

		Vivamus venenatis est at mi dapibus posuere. Nam ac nisl sed sapien rutrum sollicitudin id quis sapien. Integer malesuada euismod auctor. Phasellus rhoncus tortor ut turpis dignissim, quis mollis nibh scelerisque. Suspendisse at porta ante, sit amet porttitor enim. Cras metus erat, finibus elementum mauris ut, tincidunt venenatis sem. In bibendum, dolor non faucibus accumsan, sem nunc pellentesque nunc, eu suscipit ex ligula vitae urna. Curabitur vitae mollis sapien.
	</p>
	<br><hr><br>
	<h1 class="">Metodologia</h1>
	<br>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sem elit, eleifend ac ullamcorper in, egestas nec nunc. Aenean quis tempus lorem. Nullam at sodales ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis a rutrum libero. Ut arcu elit, hendrerit quis posuere quis, efficitur et odio. Vestibulum odio lacus, malesuada nec vehicula quis, posuere nec justo.
	</p>
	<img src="img/img.png" class="w-50 image-intro1 ">
	<p><b>Figura: </b> Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
	<br>
	<img src="img/img.png" class="w-50 image-intro2 ">
	<p><b>Figura: </b> Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
	<br>
	<img src="img/img.png" class="w-50 image-intro3 ">
	<p><b>Figura: </b> Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
	<br>
	<img src="img/img.png" class="w-50 image-intro4 ">
	<p><b>Figura: </b>  Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
	<br><hr><br>
	<p>
		Maecenas vel tempus nibh. Duis dapibus finibus justo ultrices rutrum. Sed bibendum malesuada sem ut gravida. Maecenas ligula quam, pellentesque sit amet sapien sed, molestie tristique risus. Vivamus sed fermentum dolor. Nullam sagittis cursus tellus sit amet rhoncus. Suspendisse condimentum mollis pharetra. Donec sit amet tristique lorem. Fusce nulla lectus, ullamcorper eget laoreet et, condimentum a lacus. Nullam pellentesque erat sit amet velit dapibus porta. Suspendisse potenti. Sed tempor lorem in posuere auctor. Donec fermentum ultrices tortor. Nullam egestas ipsum ut magna iaculis blandit.

		Nulla facilisi. Nam cursus maximus commodo. Curabitur posuere augue sit amet enim imperdiet scelerisque. In sit amet nibh eu turpis viverra dignissim quis eu leo. Sed ac dictum augue. Vestibulum sit amet enim vel odio maximus bibendum. Nullam porttitor tristique quam, ac pharetra enim gravida molestie. Vestibulum vel mattis arcu, tristique ultrices enim.

		Aenean gravida ultrices facilisis. Aenean venenatis nisl elit, in cursus nunc blandit et. Pellentesque ante felis, mollis et urna id, egestas condimentum tellus. Donec dui turpis, ultrices viverra accumsan eu, pretium ac ante. Curabitur imperdiet velit velit, ultricies mattis leo laoreet porta. Donec accumsan pellentesque sapien, in condimentum risus mollis ut. Vivam
	</p>
</div>
</section>

<script>
	$(window).on("scroll load3",function(){
		var aparecer = 50; 
		var eleHeight = $('.image-intro1').outerHeight(); 
		var eleTopo = $('.image-intro1').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".image-intro1").css("animation", "panoramaL 1s 1")
			$(".image-intro1").css("-webkit-animation-fill-mode", "forwards")
		}
	})

	$(window).on("scroll load4",function(){
		var aparecer = 50; 
		var eleHeight = $('.image-intro2').outerHeight(); 
		var eleTopo = $('.image-intro2').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".image-intro2").css("animation", "panoramaR 1s 1")
			$(".image-intro2").css("-webkit-animation-fill-mode", "forwards")
		}
	})

	$(window).on("scroll load5",function(){
		var aparecer = 50; 
		var eleHeight = $('.image-intro3').outerHeight(); 
		var eleTopo = $('.image-intro3').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".image-intro3").css("animation", "panoramaL 1s 1")
			$(".image-intro3").css("-webkit-animation-fill-mode", "forwards")
		}
	})

	$(window).on("scroll load6",function(){
		var aparecer = 50; 
		var eleHeight = $('.image-intro4').outerHeight(); 
		var eleTopo = $('.image-intro4').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".image-intro4").css("animation", "panoramaR 1s 1")
			$(".image-intro4").css("-webkit-animation-fill-mode", "forwards")
		}
	})
</script>