<?php include("navbar.phtml") ?>


<br><br>

<section class="section">
	<div class="text-center p-4 rounded-3 m-auto bg-light" style="width: 90%">
			<h1 class="">
				 Valoração dos Especialistas do Mercado 
			</h1>
			<br>
			<p>
				Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
			</p>
			<br>
			<div class="row">
				<div class="col">
					<button class="btn btn-success btn-ger-var float-start"> <i class="fa-solid fa-plus"></i> Adicionar Valor</button>
				</div>
				<div class="col">
					<div class="rounded-pill bg-success search-indexes p-1" style="width: 230px;float: right">
						<i class="fa-solid fa-magnifying-glass text-white"></i> 
						<input type="text" name="" placeholder="Procurar" class="rounded-pill bg-white">
					</div>
				</div>
			</div>
			<br><br>
			<div class="bg-white p-4 rounded-3" style="overflow-x: scroll; overflow-y: scroll">
				<div class="val-ilum" style="opacity: 0">
					<p class="text-green"><b>1- Iluminação</b></p>
					<br>
					<table class="text-center m-auto" style="color: black; width: 90%">
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Mês</b>
							</td>
							<td>jan/19</td>
							<td>fev/19</td>
							<td>mar/19</td>
							<td>abr/19</td>
							<td>jun/19</td>
							<td>...</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>FP</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>P</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
					</table>
				</div>
				<br>
				<div class="val-cond" style="opacity: 0">
					<p class="text-green"><b>2- Condicionamento de Ambiente</b></p>
					<br>
					<table class="text-center m-auto" style="color: black; width: 90%">
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Mês</b>
							</td>
							<td>jan/19</td>
							<td>fev/19</td>
							<td>mar/19</td>
							<td>abr/19</td>
							<td>jun/19</td>
							<td>...</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>FP</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>P</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
					</table>
				</div>
				
				<br>
				<div class="val-aut" style="opacity: 0">
					<p class="text-green"><b>3- Automação Elétrica e Sensor de Presença</b></p>
					<br>
					<table class="text-center m-auto" style="color: black; width: 90%">
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Mês</b>
							</td>
							<td>jan/19</td>
							<td>fev/19</td>
							<td>mar/19</td>
							<td>abr/19</td>
							<td>jun/19</td>
							<td>...</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>FP</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>P</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
					</table>
				</div>
				
				<br>

				<div class="val-migr" style="opacity: 0">
					<p class="text-green"><b>4- Migração do ACR ao ACL</b></p>
					<br>
					<table class="text-center m-auto" style="color: black; width: 90%">
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Mês</b>
							</td>
							<td>jan/19</td>
							<td>fev/19</td>
							<td>mar/19</td>
							<td>abr/19</td>
							<td>jun/19</td>
							<td>...</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>FP</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>P</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
					</table>
				</div>
				
				<br>
				<div class="val-efi" style="opacity: 0">
					<p class="text-green"><b>5- Eficiência Tributária</b></p>
					<br>
					<table class="text-center m-auto" style="color: black; width: 90%">
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Mês</b>
							</td>
							<td>jan/19</td>
							<td>fev/19</td>
							<td>mar/19</td>
							<td>abr/19</td>
							<td>jun/19</td>
							<td>...</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>FP</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>P</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
					</table>
				</div>
				
				<br>

				<div class="val-ajust" style="opacity: 0">
					<p class="text-green"><b>6- Ajuste da Demanda Contratada</b></p>
					<br>
					<table class="text-center m-auto" style="color: black; width: 90%">
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Mês</b>
							</td>
							<td>jan/19</td>
							<td>fev/19</td>
							<td>mar/19</td>
							<td>abr/19</td>
							<td>jun/19</td>
							<td>...</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>FP</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>P</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
					</table>
				</div>
				
				<br>

				<div class="val-sis" style="opacity: 0">
					<p class="text-green"><b>7- Sistema para monitoramento do consumo de energia</b></p>
					<br>
					<table class="text-center m-auto" style="color: black; width: 90%">
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Mês</b>
							</td>
							<td>jan/19</td>
							<td>fev/19</td>
							<td>mar/19</td>
							<td>abr/19</td>
							<td>jun/19</td>
							<td>...</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>FP</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>P</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
					</table>
				</div>
				
				<br>

				<div class="val-aco" style="opacity: 0">
					<p class="text-green"><b>8- Ações Educativas</b></p>
					<br>
					<table class="text-center m-auto" style="color: black; width: 90%">
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Mês</b>
							</td>
							<td>jan/19</td>
							<td>fev/19</td>
							<td>mar/19</td>
							<td>abr/19</td>
							<td>jun/19</td>
							<td>...</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>FP</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>P</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
					</table>
				</div>
				
				<br>

				<div class="val-class" style="opacity: 0">
					<p class="text-green"><b>9- Classificação Tarifária</b></p>
					<br>
					<table class="text-center m-auto" style="color: black; width: 90%">
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Mês</b>
							</td>
							<td>jan/19</td>
							<td>fev/19</td>
							<td>mar/19</td>
							<td>abr/19</td>
							<td>jun/19</td>
							<td>...</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>FP</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>P</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
					</table>
				</div>
				
				<br>

				<div class="val-inst" style="opacity: 0">
					<p class="text-green"><b>10- Instalação de Gerador a Diesel e Placas Solares</b></p>
					<br>
					<table class="text-center m-auto" style="color: black; width: 90%">
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Mês</b>
							</td>
							<td>jan/19</td>
							<td>fev/19</td>
							<td>mar/19</td>
							<td>abr/19</td>
							<td>jun/19</td>
							<td>...</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>FP</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="tr-3">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>P</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
						<tr class="bg-light">
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>Total</b>
							</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td>00.000,00 KWh</td>
							<td class="tr-1" style="border-bottom: 1px solid white">
								<b>00.000,00 KWh</b>
							</td>
						</tr>
					</table>
				</div>
				
				<br>
			</div>
	</div>
</section>

<div class="container-black container-ger-var fixed-top w-100 h-100 d-none">
	<div class="bg-white w-75 m-auto text-center rounded-3 mt-4 p-2 custom-input">
		<i class="fa-solid fa-xmark" style="font-size: 30px; cursor: pointer; margin-left: 90%; margin-top: 20px"></i>
		<h3 class="text-success">Gerenciar Valores</h3>
		<hr>
		<br>
		<form class="add-indice w-75 m-auto rounded-3 p-3" style="border: 1px solid lightgray">
			<p class="text-green"><b>Adicionar Valoração <i class="fa-solid fa-plus"></i></b></p>
			Nome: <input type="text" name="">
			<br><br>
			Numeração: <input type="text" name="">
			<br><br>
			Valor: 
			<select>
				<option>-</option>
				<option>Otimista</option>
				<option>Pessimista</option>
				<option>Indiferente</option>
			</select>
			<br><br>
			<button class="btn btn-green  btn-div-add-mes">Adicionar</button>
			<br>
		</form>
		<br><br>
	</div>	
</div>

<script>
	$(window).on("scroll load",function(){
	var aparecer = 50; 
	var eleHeight = $('.val-ilum').outerHeight(); 
	var eleTopo = $('.val-ilum').offset().top; 
	var scrlTopo = $(window).scrollTop(); 
	var distance = eleTopo-scrlTopo; 
	var altJanela = window.innerHeight; 
	if(distance <= altJanela-(eleHeight*(aparecer/100))) {
		$(".val-ilum").css("animation", "fade 1.5s 1")
		$(".val-ilum").css("-webkit-animation-fill-mode", "forwards")
	}
})

	$(window).on("scroll load1",function(){
	var aparecer = 50; 
	var eleHeight = $('.val-cond').outerHeight(); 
	var eleTopo = $('.val-cond').offset().top; 
	var scrlTopo = $(window).scrollTop(); 
	var distance = eleTopo-scrlTopo; 
	var altJanela = window.innerHeight; 
	if(distance <= altJanela-(eleHeight*(aparecer/100))) {
		$(".val-cond").css("animation", "fade 1.5s 1")
		$(".val-cond").css("-webkit-animation-fill-mode", "forwards")
	}
})

	$(window).on("scroll load2",function(){
	var aparecer = 50; 
	var eleHeight = $('.val-aut').outerHeight(); 
	var eleTopo = $('.val-aut').offset().top; 
	var scrlTopo = $(window).scrollTop(); 
	var distance = eleTopo-scrlTopo; 
	var altJanela = window.innerHeight; 
	if(distance <= altJanela-(eleHeight*(aparecer/100))) {
		$(".val-aut").css("animation", "fade 1.5s 1")
		$(".val-aut").css("-webkit-animation-fill-mode", "forwards")
	}
	})

	$(window).on("scroll load3",function(){
	var aparecer = 50; 
	var eleHeight = $('.val-migr').outerHeight(); 
	var eleTopo = $('.val-migr').offset().top; 
	var scrlTopo = $(window).scrollTop(); 
	var distance = eleTopo-scrlTopo; 
	var altJanela = window.innerHeight; 
	if(distance <= altJanela-(eleHeight*(aparecer/100))) {
		$(".val-migr").css("animation", "fade 1.5s 1")
		$(".val-migr").css("-webkit-animation-fill-mode", "forwards")
	}
})

	$(window).on("scroll load4",function(){
	var aparecer = 50; 
	var eleHeight = $('.val-efi').outerHeight(); 
	var eleTopo = $('.val-efi').offset().top; 
	var scrlTopo = $(window).scrollTop(); 
	var distance = eleTopo-scrlTopo; 
	var altJanela = window.innerHeight; 
	if(distance <= altJanela-(eleHeight*(aparecer/100))) {
		$(".val-efi").css("animation", "fade 1.5s 1")
		$(".val-efi").css("-webkit-animation-fill-mode", "forwards")
	}
	})

	$(window).on("scroll load5",function(){
	var aparecer = 50; 
	var eleHeight = $('.val-ajust').outerHeight(); 
	var eleTopo = $('.val-ajust').offset().top; 
	var scrlTopo = $(window).scrollTop(); 
	var distance = eleTopo-scrlTopo; 
	var altJanela = window.innerHeight; 
	if(distance <= altJanela-(eleHeight*(aparecer/100))) {
		$(".val-ajust").css("animation", "fade 1.5s 1")
		$(".val-ajust").css("-webkit-animation-fill-mode", "forwards")
	}
	})

	$(window).on("scroll load6",function(){
	var aparecer = 50; 
	var eleHeight = $('.val-sis').outerHeight(); 
	var eleTopo = $('.val-sis').offset().top; 
	var scrlTopo = $(window).scrollTop(); 
	var distance = eleTopo-scrlTopo; 
	var altJanela = window.innerHeight; 
	if(distance <= altJanela-(eleHeight*(aparecer/100))) {
		$(".val-sis").css("animation", "fade 1.5s 1")
		$(".val-sis").css("-webkit-animation-fill-mode", "forwards")
	}
	})

	$(window).on("scroll load7",function(){
	var aparecer = 50; 
	var eleHeight = $('.val-aco').outerHeight(); 
	var eleTopo = $('.val-aco').offset().top; 
	var scrlTopo = $(window).scrollTop(); 
	var distance = eleTopo-scrlTopo; 
	var altJanela = window.innerHeight; 
	if(distance <= altJanela-(eleHeight*(aparecer/100))) {
		$(".val-aco").css("animation", "fade 1.5s 1")
		$(".val-aco").css("-webkit-animation-fill-mode", "forwards")
	}
	})

	$(window).on("scroll load8",function(){
	var aparecer = 50; 
	var eleHeight = $('.val-class').outerHeight(); 
	var eleTopo = $('.val-class').offset().top; 
	var scrlTopo = $(window).scrollTop(); 
	var distance = eleTopo-scrlTopo; 
	var altJanela = window.innerHeight; 
	if(distance <= altJanela-(eleHeight*(aparecer/100))) {
		$(".val-class").css("animation", "fade 1.5s 1")
		$(".val-class").css("-webkit-animation-fill-mode", "forwards")
	}
	})

	$(window).on("scroll load9",function(){
	var aparecer = 50; 
	var eleHeight = $('.val-inst').outerHeight(); 
	var eleTopo = $('.val-inst').offset().top; 
	var scrlTopo = $(window).scrollTop(); 
	var distance = eleTopo-scrlTopo; 
	var altJanela = window.innerHeight; 
	if(distance <= altJanela-(eleHeight*(aparecer/100))) {
		$(".val-inst").css("animation", "fade 1.5s 1")
		$(".val-inst").css("-webkit-animation-fill-mode", "forwards")
	}
	})
</script>