<nav class="navbar navbar-expand-lg navbar-light bg-success navbar-index">
  <div class="container-fluid">
    <a class="navbar-brand ms-1" href="#" style="margin-right: 40%">
    	<img src="img/logo-branca.png" style="width: 200px">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 row">
        <li class="nav-item col">
          <a class="nav-link text-white" aria-current="page" href="/index">Contato</a>
        </li>
        <li class="nav-item col">
          <a class="nav-link text-white" aria-current="page" href="/index">Suporte</a>
        </li>
       	<li class="nav-item col">
          <a class="nav-link text-danger text-center" href="/index">Sair</a>
        </li>

        <li class="nav-item col">
          <a class="nav-link" href="#">
          	<img src="img/dna_trans.png" style="width: 50px">
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!--- FIM NAVBARS --->


<br>
<div class="row text-center nav-painel text-success">
	<div class="col">
		<a href="/introduction" class="intro"><i class="fa-regular fa-file-lines"></i> Introdução </a>
	</div>
	|
	<div class="col">
		<a href="/admin" class="admin"><i class="fa-solid fa-eye"></i>  Administrador</a>
	</div>
	|
	<div class="col">
		<a href="/consumption" class="consumo"><i class="fa-solid fa-chart-line"></i> Consumo</a>
	</div>
	|
	<div class="col dropdown">
		
		<button class="dropdown-toggle bg-white border-0" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
   			<a href="" class="premissa"><i class="fa-solid fa-circle-info"></i> Premissa</a>
  		</button>
  		<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
		    <li>
		    	<a class="dropdown-item indices" href="/indexes">
		    		<i class="fa-solid fa-list"></i> Índices</a>
		    </li>
		    <li>
		    	<a class="dropdown-item fontesEnerg" href="/energy_sources">
		    		<i class="fa-solid fa-bolt"></i> Fontes Energéticas</a>
		    </li>
		</ul>
	</div>
	|
	<div class="col">
		<a href="/res_energy" class="rec-ener"><i class="fa-solid fa-solar-panel"></i> Rec. Energéticos</a>
	</div>
	|
	<div class="col">
		<div class="col dropdown">
		<button class="dropdown-toggle bg-white border-0" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
   			<a href=""><i class="fa-solid fa-magnifying-glass"></i> Análise</a>
  		</button>
  		<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
		    <li>
		    	<a class="dropdown-item espec-merc" href="/market_experts">
		    		<i class="fa-solid fa-chalkboard-user"></i> Especialistas do Mercado
		    	</a>
		    </li>
		    <li>
		    	<a class="dropdown-item opin-stake" href="/opinion_stake">
		    		<i class="fa-solid fa-comments"></i> Opinião dos Stakeholders</a>
		    </li>
		     <li>
		    	<a class="dropdown-item result-anali" href="/result_of_analysis">
		    		<i class="fa-solid fa-square-poll-vertical"></i> Resultados das Análises</a>
		    </li>
		     <li>
		    	<a class="dropdown-item valoracoes" href="/valuation">
		    		<i class="fa-solid fa-percent"></i> Valorações</a>
		    </li>
		</ul>
	</div>
	</div>
	|
	<div class="col">
		<a href="/references" class="refe"><i class="fa-solid fa-book"></i> Referências</a>
	</div>
</div>