<?php include("navbar.phtml") ?>


<br><br>

<section class="section">
	<div class="text-center p-4 rounded-3 m-auto bg-light" style="width: 90%">
			<h1 class="">
					Opinião dos Stakeholders
			</h1>
			<br>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sem elit, eleifend ac ullamcorper in, egestas nec nunc. Aenean quis tempus lorem.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sem elit, eleifend ac ullamcorper in, egestas nec nunc. Aenean quis tempus lorem.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sem elit, eleifend ac ullamcorper in, egestas nec nunc. Aenean quis tempus lorem.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sem elit, eleifend ac ullamcorper in, egestas nec nunc. Aenean quis tempus lorem.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sem elit, eleifend ac ullamcorper in, egestas nec nunc. Aenean quis tempus lorem.
			</p>
			<br>
			<div class="row">
				<div class="col">
					<button class="btn btn-success btn-ger-depart"> <i class="fa-solid fa-plus"></i> Adicionar Departamento</button>
				</div>
			</div>
			<br><br>
			<div class="bg-white p-4 rounded-3" style="overflow-x: scroll; overflow-y: scroll">
				<p class="text-green"><b>Setor Responsabilidade Social e Ambiental</b></p>
				<br>
				<div class="row row-1" style="opacity: 0">
					<div class="col m-3 p-3 rounded-3 bg-light">
						<p class="text-success"><b>Departamento Diretoria</b></p>
						<table class="text-center m-auto" style="color: black; width: 90%">
							<tr class="tr-1">
								<td>Dimensão</td>
								<td>Valor</td>
							</tr>
							<tr class="tr-2">
								<td>Ambiental</td>
								<td>0%</td>
							</tr>
							<tr class="tr-3">
								<td>Social</td>
								<td>0%</td>
							</tr>
						</table>
					</div>
					<div class="col m-3 p-3 rounded-3 bg-light">
						<p class="text-success"><b>Departamento Analista</b></p>
						<table class="text-center m-auto" style="color: black; width: 90%">
							<tr class="tr-1">
								<td>Dimensão</td>
								<td>Valor</td>
							</tr>
							<tr class="tr-2">
								<td>Ambiental</td>
								<td>0%</td>
							</tr>
							<tr class="tr-3">
								<td>Social</td>
								<td>0%</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
			<br><br>
			<div class="bg-white p-4 rounded-3" style="overflow-x: scroll; overflow-y: scroll">
				<p class="text-green"><b>Setor Unidade</b></p>
				<br>
				<div class="row row-2" style="opacity: 0">
					<div class="col m-3 p-3 rounded-3 bg-light">
						<p class="text-success"><b>Departamento Diretoria</b></p>
						<table class="text-center m-auto" style="color: black; width: 90%">
							<tr class="tr-1">
								<td>Dimensão</td>
								<td>Valor</td>
							</tr>
							<tr class="tr-2">
								<td>Ambiental</td>
								<td>0%</td>
							</tr>
							<tr class="tr-3">
								<td>Social</td>
								<td>0%</td>
							</tr>
						</table>
					</div>
					<div class="col m-3 p-3 rounded-3 bg-light">
						<p class="text-success"><b>Departamento Especialista</b></p>
						<table class="text-center m-auto" style="color: black; width: 90%">
							<tr class="tr-1">
								<td>Dimensão</td>
								<td>Valor</td>
							</tr>
							<tr class="tr-2">
								<td>Ambiental</td>
								<td>0%</td>
							</tr>
							<tr class="tr-3">
								<td>Social</td>
								<td>0%</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
			<br><br>
			<div class="bg-white p-4 rounded-3" style="overflow-x: scroll; overflow-y: scroll">
				<p class="text-green"><b>Setor Suprimentos</b></p>
				<br>
				<div class="row row-3" style="opacity: 0">
					<div class="col m-3 p-3 rounded-3 bg-light">
						<p class="text-success"><b>Departamento Gerência</b></p>
						<table class="text-center m-auto" style="color: black; width: 90%">
							<tr class="tr-1">
								<td>Dimensão</td>
								<td>Valor</td>
							</tr>
							<tr class="tr-2">
								<td>Ambiental</td>
								<td>0%</td>
							</tr>
							<tr class="tr-3">
								<td>Social</td>
								<td>0%</td>
							</tr>
						</table>
					</div>
					<div class="col m-3 p-3 rounded-3 bg-light">
						<p class="text-success"><b>Departamento Especialista</b></p>
						<table class="text-center m-auto" style="color: black; width: 90%">
							<tr class="tr-1">
								<td>Dimensão</td>
								<td>Valor</td>
							</tr>
							<tr class="tr-2">
								<td>Ambiental</td>
								<td>0%</td>
							</tr>
							<tr class="tr-3">
								<td>Social</td>
								<td>0%</td>
							</tr>
						</table>
					</div>
				</div>
			</div>

			<br><br>
			<div class="bg-white p-4 rounded-3" style="overflow-x: scroll; overflow-y: scroll">
				<p class="text-green"><b>Setor Área Técnica</b></p>
				<br>
				<div class="row row-4" style="opacity: 0">
					<div class="col m-3 p-3 rounded-3 bg-light">
						<p class="text-success"><b>Departamento Gerência</b></p>
						<table class="text-center m-auto" style="color: black; width: 90%">
							<tr class="tr-1">
								<td>Dimensão</td>
								<td>Valor</td>
							</tr>
							<tr class="tr-2">
								<td>Ambiental</td>
								<td>0%</td>
							</tr>
							<tr class="tr-3">
								<td>Social</td>
								<td>0%</td>
							</tr>
						</table>
					</div>
					<div class="col m-3 p-3 rounded-3 bg-light">
						<p class="text-success"><b>Departamento Especialista</b></p>
						<table class="text-center m-auto" style="color: black; width: 90%">
							<tr class="tr-1">
								<td>Dimensão</td>
								<td>Valor</td>
							</tr>
							<tr class="tr-2">
								<td>Ambiental</td>
								<td>0%</td>
							</tr>
							<tr class="tr-3">
								<td>Social</td>
								<td>0%</td>
							</tr>
						</table>
					</div>
				</div>
			</div>
	</div>
</section>

<div class="container-black container-ger-depart fixed-top w-100 h-100 d-none">
	<div class="custom-input bg-white w-75 m-auto text-center rounded-3 mt-4 p-2">
		<i class="fa-solid fa-xmark" style="font-size: 30px; cursor: pointer; margin-left: 90%; margin-top: 20px"></i>
		<br>
		<form class=" w-75 m-auto rounded-3 p-3 text-start" style="border: 1px solid lightgray">
			<p class="text-green text-center"><b>Adicionar Departamento <i class="fa-solid fa-plus"></i></b></p>
			<p class="text-warning fst-italic text-center" style="font-size: 12px">
				Inserir peso percentual de cada dimensão. A somatória dos pesos das 4 dimensões NÃO pode ser maior do que 100%
			</p>
			<hr>
			
			Departamento: 
			<select>
				<option>Responsabilidade Social e Ambiental</option>
				<option>Unidade</option>
				<option>Área Técnica</option>
				<option>Planejamento e Operações</option>
			</select>
			<br><br>
			Cargo: 
			<select>
				<option>Gerência</option>
				<option>Especialista</option>
				<option>Área Técnica</option>
			</select>
			<br><br>
			Social: <input type="text" name="">
			<br><br>
			Política: <input type="text" name="">
			<br><br>
			Ambiental: <input type="text" name="">
			<br><br>
			Técnica-Econômica: <input type="text" name="">
			<br><br>
			<div class="m-auto text-center">
				<button class="btn btn-green  btn-div-add-mes">Adicionar</button>
			</div>
			<br>
		</form>
		<br><br>
	</div>	
</div>

<script>
	$(window).on("scroll load1",function(){
		var aparecer = 50; 
		var eleHeight = $('.row-1').outerHeight(); 
		var eleTopo = $('.row-1').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".row-1").css("animation", "fade 1.5s 1")
			$(".row-1").css("-webkit-animation-fill-mode", "forwards")
		}
	})

	$(window).on("scroll load2",function(){
		var aparecer = 50; 
		var eleHeight = $('.row-2').outerHeight(); 
		var eleTopo = $('.row-2').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".row-2").css("animation", "fade 1.5s 1")
			$(".row-2").css("-webkit-animation-fill-mode", "forwards")
		}
	})

	$(window).on("scroll load3",function(){
		var aparecer = 50; 
		var eleHeight = $('.row-3').outerHeight(); 
		var eleTopo = $('.row-3').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".row-3").css("animation", "fade 1.5s 1")
			$(".row-3").css("-webkit-animation-fill-mode", "forwards")
		}
	})

	$(window).on("scroll load4",function(){
		var aparecer = 50; 
		var eleHeight = $('.row-4').outerHeight(); 
		var eleTopo = $('.row-4').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".row-4").css("animation", "fade 1.5s 1")
			$(".row-4").css("-webkit-animation-fill-mode", "forwards")
		}
	})
</script>