<?php include("navbar.phtml") ?>


<br><br>

<section class="section">
	<div class="text-center p-4 rounded-3 m-auto bg-light" style="width: 90%">
	<h1 class="">
		Referências Bibliográficas
	</h1>
	<br>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sem elit, eleifend ac ullamcorper in, egestas nec nunc. Aenean quis tempus lorem. Nullam at sodales ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis a rutrum libero. Ut arcu elit, hendrerit quis posuere quis, efficitur et odio. Vestibulum odio lacus, malesuada nec vehicula quis, posuere nec justo. Etiam in eros arcu. Proin at sem massa. Nullam eget ante feugiat, dignissim enim quis, elementum augue. Vestibulum in aliquam enim. Aenean dolor nibh, euismod id massa eget, convallis cursus sem. Nunc ullamcorper enim a nunc porta finibus. Ut quis ornare nibh. Maecenas iaculis lacus at dolor venenatis suscipit.

Vivamus venenatis est at mi dapibus posuere. Nam ac nisl sed sapien rutrum sollicitudin id quis sapien. Integer malesuada euismod auctor. Phasellus rhoncus tortor ut turpis dignissim, quis mollis nibh scelerisque. Suspendisse at porta ante, sit amet porttitor enim. Cras metus erat, finibus elementum mauris ut, tincidunt venenatis sem. In bibendum, dolor non faucibus accumsan, sem nunc pellentesque nunc, eu suscipit ex ligula vitae urna. Curabitur vitae mollis sapien.

Maecenas vel tempus nibh. Duis dapibus finibus justo ultrices rutrum. Sed bibendum malesuada sem ut gravida. Maecenas ligula quam, pellentesque sit amet sapien sed, molestie tristique risus. Vivamus sed fermentum dolor. Nullam sagittis cursus tellus sit amet rhoncus. Suspendisse condimentum mollis pharetra. Donec sit amet tristique lorem. Fusce nulla lectus, ullamcorper eget laoreet et, condimentum a lacus. Nullam pellentesque erat sit amet velit dapibus porta. Suspendisse potenti. Sed tempor lorem in posuere auctor. Donec fermentum ultrices tortor. Nullam egestas ipsum ut magna iaculis blandit.
	</p>
</div>
</section>