<?php include("navbar.phtml") ?>


<br><br>

<section class="section">
	<div class="text-center p-4 rounded-3 m-auto bg-light" style="width: 90%">
		<button class="btn float-start btn-gray-opp rounded-circle" title="Voltar">
			<a href="/res_energy" class="text-white">
				<i class="fa-solid fa-rotate-left "></i>
			</a>
		</button>
	<h1 class="">
		Recurso Tributário
	</h1>
	<br>
	<p>
		Analisa possíveis ganhos com gestão tributária da conta de energia elétrica, por exemplo, isenção ou redução de ICMS.
	</p>

	<div class="img-principal-recursos">
		<img src="img/graph-tela.webp" class="w-50 img-rec">
	</div>

	<br><br>
	<div class="row">
		<div class="col">
			<button class="btn btn-success btn-add-mes float-start"><i class="fa-solid fa-plus"></i> Adicionar um mês</button>
		</div>
		<div class="col">
			<button class="btn btn-success btn-ger-func"> <i class="fa-solid fa-id-card"></i> Gerenciar Funcionários</button>
		</div>
		<div class="col">
			<button class="btn btn-success btn-ger-var"> <i class="fa-solid fa-calculator"></i> Gerenciar Variáveis</button>
		</div>
		<div class="col">
			<div class="rounded-pill bg-success search-indice p-1 custom-input" style="width: 230px;float: right">
				<i class="fa-solid fa-magnifying-glass text-white"></i> 
				<input type="text" name="" placeholder="Procurar" class="rounded-pill bg-white">
			</div>
		</div>
		<br><br><br>
		<div class="bg-white m-auto p-4 rounded-3 custom-input" style="width: 90%; overflow-x: scroll; overflow-y: scroll">
			<table class="text-center m-auto w-75 table-1" style="min-width: 2000px; opacity: 0">
				<tr class="tr-1">
					<td>
						Mês
					</td>
					<td>
						Ano
					</td>
					<td>
						Energia R$
					</td>
					<td>
						Tusd na conta R$
					</td>
					<td>Economia R$</td>
					<td>Fee mês R$</td>
					<td>Investimento R$</td>
					<td>Resultado Operacional R$</td>
					<td>Ganho Financeiro R$</td>
					<td>Resultado Líquido R$</td>
					<td>
						Opções
					</td>
				</tr>
				<tr class="tr-2">
					<td>
						12
					</td>
					<td>
						2020
					</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>
						00,00
					</td>
					<td>0,00</td>
					<td>0,00</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>00,00</td>
					<td>0,00</td>
					<td>000</td>
					<td>
						<i class="fa-solid fa-pen text-dark edit-line text-warning" title="Editar"></i>
							<i class="fa-solid fa-floppy-disk ms-2 save-line-disabled" title="Salvar" style="color: lightgray"></i>
							<i class="fa-solid fa-floppy-disk text-success ms-2 d-none save-line" title="Salvar"></i>
							<i class="fa-solid fa-trash-can text-danger ms-2"></i>
					</td>
				</tr>

				<tr class="tr-3">
					<td>
						12
					</td>
					<td>
						2020
					</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>
						00,00
					</td>
					<td>0,00</td>
					<td>0,00</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>00,00</td>
					<td>0,00</td>
					<td>000</td>
					<td>
						<i class="fa-solid fa-pen text-dark edit-line text-warning" title="Editar"></i>
							<i class="fa-solid fa-floppy-disk ms-2 save-line-disabled" title="Salvar" style="color: lightgray"></i>
							<i class="fa-solid fa-floppy-disk text-success ms-2 d-none save-line" title="Salvar"></i>
							<i class="fa-solid fa-trash-can text-danger ms-2"></i>
					</td>
				</tr>
			</table>
		</div>
		<div class="economy bg-gray rounded-3 m-auto p-4 mt-4" style="width: 90%">
		<h3>Economia</h3>
		<br>
		<div class="bg-white m-auto p-4 rounded-3" style="width: 90%; overflow-x: scroll; overflow-y: scroll">
		<br>
		<div class="bg-white m-auto p-4 rounded-3" style="width: 90%; overflow-x: scroll; overflow-y: scroll">
			<table class="text-center m-auto w-75 text-dark">
				<tr class="tr-1">
					<td>
						Dado
					</td>
					<td>
						Valor
					</td>
				</tr>
				<tr class="tr-2">
					<td>
						Vida Útil - LED
					</td>
					<td>
						00,00
					</td>
				</tr>

				<tr class="tr-3">
					<td>
						Vida Útil - LED
					</td>
					<td>
						00,00
					</td>
				</tr>
			</table>
		</div>
		<br>
		<div class="bg-white m-auto p-4 rounded-3" style="width: 90%; overflow-x: scroll; overflow-y: scroll">
			<table class="text-center m-auto w-75 text-dark">
				<tr class="tr-1">
					<td>
						Dado
					</td>
					<td>
						Valor
					</td>
				</tr>
				<tr class="tr-2">
					<td>
						Vida Útil - LED
					</td>
					<td>
						00,00
					</td>
				</tr>

				<tr class="tr-3">
					<td>
						Vida Útil - LED
					</td>
					<td>
						00,00
					</td>
				</tr>
			</table>
		</div>
	</div>
	</div>
</div>
</section>

<div class="container-black container-add-mes fixed-top w-100 h-100 d-none">
	<div class="div-modal custom-input bg-white w-75 m-auto text-center rounded-3 mt-4 p-2">
		<i class="fa-solid fa-xmark" style="font-size: 30px; cursor: pointer; margin-left: 90%; margin-top: 20px"></i>
		<h3 class="text-success">Adicionar um mês</h3>
		<hr>
		<br>
		<form>
			<i class="fa-solid fa-dollar-sign"></i> Energia: 
			<input type="text" name="email"class="bg-light" value="0">

			<i class="fa-solid fa-dollar-sign ms-4"></i> Investimento: 
			<input type="text" name="email"class="bg-light" value="0">

			<i class="fa-solid fa-calendar-days ms-4"></i>Mês: 
			<input type="text" name="email" class="bg-light" value="0" style="width: 50px">
			<br><br>
			<button class="btn btn-green btn-div-add-mes">Adicionar +</button>
			<br><br>
		</form>
	</div>	
</div>


<div class="container-black container-ger-var fixed-top w-100 h-100 d-none">
	<div class="div-modal custom-input bg-white w-75 m-auto text-center rounded-3 mt-4 p-2">
		<i class="fa-solid fa-xmark" style="font-size: 30px; cursor: pointer; margin-left: 90%; margin-top: 20px"></i>
		<h3 class="text-success">Gerenciar Variáveis</h3>
		<hr>
		<br>
		<form class="w-75 m-auto rounded-3 p-3" style="border: 1px solid lightgray">
			<p class="text-green"><b>Adicionar Variável +</b></p>
			<div class="row"> 
				<div class="col">
			% da TUSD na conta de energia: <input type="text" name="" value="30">
				</div>
			</div>
			<br>
			<div class="row">
				<div class="col">
					FEE Negociado: <input type="text" name="" value="8">	
				</div>
				<div class="col">
			ICMS: <input type="text" name="" value="18">
				</div>
			</div>
			<br><br>
			<button class="btn btn-green btn-div-add-mes">Salvar</button>
			<br>
		</form>
		<br><br>
	</div>	
</div>


<div class="container-black container-ger-fun fixed-top w-100 h-100 d-none">
	<div class="div-modal custom-input bg-white w-75 m-auto text-center rounded-3 mt-4 p-4" style="overflow-y: scroll; overflow-x: scroll; max-height: 500px">
		<i class="fa-solid fa-xmark" style="font-size: 30px; cursor: pointer; margin-left: 90%; margin-top: 20px;"></i>
		<h3 class="text-success">Gerenciar Funcionários</h3>
		<hr>
		<br>
		<form class=" w-75 m-auto rounded-3 p-3" style="border: 1px solid lightgray">
			<p class="text-green"><b>Adicionar Funcionário</b></p>
			<div class="row"> 
				<div class="col">
			Título: <input type="text" name="">
				</div>
				<div class="col">
			Salário: <input type="text" name="">
					
				</div>
				<div class="col">
			Quantidade: <input type="text" name="">
					
				</div>
				<div class="col mt-3">
			Dias de Trabalho: <input type="text" name="">
					
					
				</div>
			</div>
			<br><br>
			<button class="btn btn-green btn-div-add-mes">Adicionar +</button>
			<br>
		</form>
		<br><br>
		<p class="text-green text-start"><b>Funcionários Cadastrados: </b></p>
		<div class="m-auto" style="overflow-x: scroll; overflow-y: scroll">
			<table class="text-center m-auto">
				<tr class="tr-1">
					<td>
						ID
					</td>
					<td>
						Título
					</td>
					<td>
						Salário
					</td>
					<td>
						Quantidade
					</td>
					<td>Dias de Trabalho</td>
					<td>Salário Anual</td>
					<td>
						Opções
					</td>
				</tr>
				<tr class="tr-2">
					<td>1</td>
					<td>
						<input type="text" name="" value="Assistente" disabled>
					</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>
						<input type="text" name="" value="2" disabled>
					</td>
					<td>
						<input type="text" name="" value="5" disabled>
					</td>
					<td>
						R$000,000
					</td>
					<td>
						<i class="fa-solid fa-pen text-dark edit-line text-warning" title="Editar"></i>
							<i class="fa-solid fa-floppy-disk ms-2 save-line-disabled" title="Salvar" style="color: lightgray"></i>
							<i class="fa-solid fa-floppy-disk text-success ms-2 d-none save-line" title="Salvar"></i>
							<i class="fa-solid fa-trash-can text-danger ms-2"></i>
					</td>
				</tr>
			</table>
		</div>
		
		<br><br>
	</div>	
</div>

<script>
	$(window).on("scroll loadEco",function(){
		var aparecer = 50; 
		var eleHeight = $('.economy').outerHeight(); 
		var eleTopo = $('.economy').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".economy").css("animation", "scaleX 2s 1")
			$(".economy").css("-webkit-animation-fill-mode", "forwards")
		}
	})

	$(window).on("scroll loadTabel",function(){
		var aparecer = 50; 
		var eleHeight = $('.table-1').outerHeight(); 
		var eleTopo = $('.table-1').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".table-1").css("animation", "fade 1s 1")
			$(".table-1").css("-webkit-animation-fill-mode", "forwards")
		}
	})
</script>