<?php include("navbar.phtml") ?>


<br><br>

<section class="section">
	<div class="text-center p-4 rounded-3 m-auto bg-light" style="width: 90%">
		<button class="btn float-start btn-gray-opp rounded-circle" title="Voltar">
			<a href="/res_energy" class="text-white">
				<i class="fa-solid fa-rotate-left "></i>
			</a>
		</button>
	<h1 class="">
		Ambiente de Contratação Livre
	</h1>
	<br>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sem elit, eleifend ac ullamcorper in, egestas nec nunc. Aenean quis tempus lorem.Lorem ipsum dolor sit amet
	</p>
	<div class="img-principal">
		<img src="img/conection.webp" class="w-50 img-rec">
	</div>
	<br><br>
	<div class="row">
		<div class="col">
			<button class="btn btn-success btn-ger-func"> <i class="fa-solid fa-id-card"></i> Gerenciar Funcionários</button>
		</div>
		<div class="col">
			<button class="btn btn-success btn-ger-var"> <i class="fa-solid fa-calculator"></i> Gerenciar Valores</button>
		</div>
		<div class="col">
			<div class="rounded-pill bg-success search-indice p-1 custom-input" style="width: 230px;float: right">
				<i class="fa-solid fa-magnifying-glass text-white"></i> 
				<input type="text" name="" placeholder="Procurar" class="rounded-pill bg-white">
			</div>
		</div>
	</div>
		<br><br><br>
		<div class="bg-white text-center p-4 rounded-3 m-auto" style="width: 90%">
			<button class="btn btn-success w-50 btn-sort-down-gerais"> Análise Financeira <i class="fa-solid fa-sort-down"></i></button>
			<button class="btn btn-success w-50 btn-sort-up-gerais d-none">Análise Financeira <i class="fa-solid fa-sort-up"></i></button>
			<br><br>
			<div class="text-center table-animate m-auto table-fontes-gerais d-none" style="color: black; width: 90%; overflow-x: scroll; overflow-y: scroll">
				<table>
				<tr class="tr-1">
					<td>
						ID
					</td>
					<td>
						Nome Modelo
					</td>
					<td>
						Potência W
					</td>
					<td>
						Quantidade
					</td>
					<td>Potência Total W</td>
					<td>Potência Total KW</td>
					<td>Consumo mês KWh</td>
					<td>Consumo mês R$</td>
					<td>Consumo ano KWh</td>
					<td>Consumo ano R$</td>
				</tr>
				<tr class="tr-2">
					<td>
						12
					</td>
					<td>
						Alógena 50W
					</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>
						00,00
					</td>
					<td>0,00</td>
					<td>0,00</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>00,00</td>
					<td>000</td>
					<td>000</td>

				</tr>

				<tr class="tr-3">
					<td>
						Fluorescente 110W
					</td>
					<td>
						2020
					</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>
						00,00
					</td>
					<td>0,00</td>
					<td>0,00</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>00,00</td>
					<td>0,00</td>
					<td>000</td>
				</tr>
			</table>
			</div>
			<hr>
			<button class="btn btn-success w-50 btn-sort-down-est"> Redução CO2 Toneladas <i class="fa-solid fa-sort-down"></i></button>
			<button class="btn btn-success w-50 btn-sort-up-est d-none"> Redução CO2 Toneladas <i class="fa-solid fa-sort-up"></i></button>
			<br><br>
			<div class="text-center table-2-cons m-auto div-fontes-estab d-none" style="color: black; width: 90%; overflow-x: scroll; overflow-y: scroll">
				<table class="enter m-auto w-75" style="min-width: 3000px">
				<tr class="tr-1">
					<td>
						ID
					</td>
					<td>
						Modelo
					</td>
					<td>Quantidade</td>
					<td>
						Potência W
					</td>
					<td>
						Eficiência Inverter
					</td>
					<td>Watts Total Convencional</td>
					<td>Watts Total Inverter</td>
					<td>KW Total Inverter</td>
					<td>TR R22</td>
					<td>Volume R22 5Kg</td>
					<td>Preço Unitário Convencional R$</td>

					<td>Preço Unitário Inverter R$</td>
					<td>KHh Inverter</td>
					<td> Redução KHh</td>
					<td>R$ Inverter</td>
					<td>Redução R$</td>
					<td>Redução %</td>
					<td>Preço Total R$</td>
					<td>Redução Tons CO2</td>
					<td>Redução M3 de Água</td>
					<td>
						Opções
					</td>
				</tr>
				<tr class="tr-3">
					<td>0</td>
					<td>
						<input type="text" name="" value="Modelo X" disabled>
					</td>
					<td>
						<input type="text" name="" value="0" disabled>
					</td>
					<td>
						<input type="text" name="" value="0" disabled>
					</td>
					<td>
						<input type="text" name="" value="0" disabled>
					</td>
					<td>
						00,00
					</td>
					<td>0,00</td>
					<td>0,00</td>
					<td>0,00</td>
					<td>0,00</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>0,00</td>
					<td>0,00</td>

					<td>00,00</td>
					<td>0,00</td>
					<td>000</td>
					<td>00,00</td>
					<td>0,00</td>
					<td>000</td>
					<td>
						<i class="fa-solid fa-pen text-dark edit-line text-warning" title="Editar"></i>
							<i class="fa-solid fa-floppy-disk ms-2 save-line-disabled" title="Salvar" style="color: lightgray"></i>
							<i class="fa-solid fa-floppy-disk text-success ms-2 d-none save-line" title="Salvar"></i>
							<i class="fa-solid fa-trash-can text-danger ms-2"></i>
					</td>
				</tr>

				<tr class="tr-2">
					<td>0</td>
					<td>
						<input type="text" name="" value="Modelo X" disabled>
					</td>
					<td>
						<input type="text" name="" value="0" disabled>
					</td>
					<td>
						<input type="text" name="" value="0" disabled>
					</td>
					<td>
						<input type="text" name="" value="0" disabled>
					</td>
					<td>
						00,00
					</td>
					<td>0,00</td>
					<td>0,00</td>
					<td>0,00</td>
					<td>0,00</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>0,00</td>
					<td>0,00</td>
					
					<td>00,00</td>
					<td>0,00</td>
					<td>000</td>
					<td>00,00</td>
					<td>0,00</td>
					<td>000</td>
					<td>
						<i class="fa-solid fa-pen text-dark edit-line text-warning" title="Editar"></i>
							<i class="fa-solid fa-floppy-disk ms-2 save-line-disabled" title="Salvar" style="color: lightgray"></i>
							<i class="fa-solid fa-floppy-disk text-success ms-2 d-none save-line" title="Salvar"></i>
							<i class="fa-solid fa-trash-can text-danger ms-2"></i>
					</td>
				</tr>
			</table>
			</div>
</div>
</section>

<div class="container-black container-ger-var-ps fixed-top w-100 h-100 d-none">
	<div class="div-modal custom-input bg-white w-75 m-auto text-center rounded-3 mt-4 p-2" style="max-height: 500px; overflow-y: scroll">
		<i class="fa-solid fa-xmark" style="font-size: 30px; cursor: pointer; margin-left: 90%; margin-top: 20px"></i>
		<form class="add-indice w-75 m-auto rounded-3 p-3 text-start" style="border: 1px solid lightgray">
			<p class="text-green text-center"><b>Variáveis Painel Solar +</b></p>
			Irradiação (kWh/m².dia): <input type="text" name="">
			<br><br>
			Potência (kWp): <input type="text" name="">
			<br><br>
			Performance Ratio (%): <input type="text" name="">
			<br><br>
			Degradação (% ao mês após 1° ano): <input type="text" name="">
			<br><br>
			Degradação 1º ano (% ao mês): <input type="text" name="">
			<br><br>
			Manutenção (% ao mês): <input type="text" name="">
			<br><br>
			Investimento inicial: <input type="text" name="">
			<br><br>
			Investimento 7º ano: <input type="text" name="">
			<br><br>
			Investimento 14º ano: <input type="text" name="">
			<br><br>
			Investimento 21º ano: <input type="text" name="">
			<br><br>
			<div class="text-center m-auto">
				<button class="btn btn-green btn-div-add-mes m-auto">Salvar</button>
			</div>
			<br>
		</form>
		<br><br>
	</div>	
</div>

<div class="container-black container-ger-var-gerador fixed-top w-100 h-100 d-none">
	<div class="div-modal bg-white w-75 m-auto text-center rounded-3 mt-4 p-2 custom-input" style="max-height: 500px; overflow-y: scroll">
		<i class="fa-solid fa-xmark" style="font-size: 30px; cursor: pointer; margin-left: 90%; margin-top: 20px"></i>
		<form class="add-indice w-75 m-auto rounded-3 p-3 text-start" style="border: 1px solid lightgray">
			<p class="text-green text-center"><b>Variáveis Gerador Solar +</b></p>
			Custo do diesel (R$/L): <input type="text" name="">
			<br><br>
			Manutenção mensal (ao mês): <input type="text" name="">
			<br><br>
			Data de assinatura: <input type="date" name="">
			<br><br>
			Data de análise: <input type="date" name="">
			<br><br>
			Funcionamento (horas por dia): <input type="text" name="">
			<br><br>
			Consumo combustível (litros/horas): <input type="text" name="">
			<br><br>
			Vazão de gases (litro/segundo): <input type="text" name="">
			<br><br>
			Vida útil (em anos): <input type="text" name="">
			<br><br>
			<div class="text-center m-auto">
				<button class="btn btn-green btn-div-add-mes m-auto">Salvar</button>
			</div>
			<br>
		</form>
		<br><br>
	</div>	
</div>

<div class="container-black container-ger-var fixed-top w-100 h-100 d-none">
	<div class="div-modal bg-white w-75 m-auto text-center rounded-3 mt-4 p-2 custom-input">
		<i class="fa-solid fa-xmark" style="font-size: 30px; cursor: pointer; margin-left: 90%; margin-top: 20px"></i>
		<h3 class="text-success">Gerenciar Valores</h3>
		<hr>
		<br>
		<form class="add-indice w-75 m-auto rounded-3 p-3" style="border: 1px solid lightgray">
			Capex para Migração: <input type="text" name="" value="30">
			<br><br>
					Success Fee da Consultoria: <input type="text" name="" value="8">
			<br><br>
			<button class="btn btn-green btn-div-add-mes">Salvar</button>
			<br>
		</form>
		<br><br>
	</div>	
</div>


<div class="container-black container-ger-fun fixed-top w-100 h-100 d-none">
	<div class="custom-input bg-white w-75 m-auto text-center rounded-3 mt-4 p-4" style="overflow-y: scroll; overflow-x: scroll; max-height: 500px">
		<i class="fa-solid fa-xmark" style="font-size: 30px; cursor: pointer; margin-left: 90%; margin-top: 20px;"></i>
		<h3 class="text-success">Gerenciar Funcionários</h3>
		<hr>
		<br>
		<form class="add-indice w-75 m-auto rounded-3 p-3" style="border: 1px solid lightgray">
			<p class="text-green"><b>Adicionar Funcionário</b></p>
			<div class="row"> 
				<div class="col">
			Título: <input type="text" name="">
				</div>
				<div class="col">
			Salário: <input type="text" name="">
					
				</div>
				<div class="col">
			Quantidade: <input type="text" name="">
					
				</div>
				<div class="col mt-3">
			Dias de Trabalho: <input type="text" name="">
					
					
				</div>
			</div>
			<br><br>
			<button class="btn btn-green btn-div-add-mes">Adicionar +</button>
			<br>
		</form>
		<br><br>
		<p class="text-green text-start"><b>Funcionários Cadastrados: </b></p>
		<div class="m-auto" style="overflow-x: scroll; overflow-y: scroll">
			<table class="text-center m-auto">
				<tr class="tr-1">
					<td>
						ID
					</td>
					<td>
						Título
					</td>
					<td>
						Salário
					</td>
					<td>
						Quantidade
					</td>
					<td>Dias de Trabalho</td>
					<td>Salário Anual</td>
					<td>
						Opções
					</td>
				</tr>
				<tr class="tr-2">
					<td>1</td>
					<td>
						<input type="text" name="" value="Assistente" disabled>
					</td>
					<td>
						<input type="text" name="" value="000,00" disabled>
					</td>
					<td>
						<input type="text" name="" value="2" disabled>
					</td>
					<td>
						<input type="text" name="" value="5" disabled>
					</td>
					<td>
						R$000,000
					</td>
					<td>
						<i class="fa-solid fa-pen text-dark edit-line text-warning" title="Editar"></i>
							<i class="fa-solid fa-floppy-disk ms-2 save-line-disabled" title="Salvar" style="color: lightgray"></i>
							<i class="fa-solid fa-floppy-disk text-success ms-2 d-none save-line" title="Salvar"></i>
							<i class="fa-solid fa-trash-can text-danger ms-2"></i>
					</td>
				</tr>
			</table>
		</div>
		
		<br><br>
	</div>	
</div>

<script>
	$(window).on("scroll loadEco",function(){
		var aparecer = 50; 
		var eleHeight = $('.economy').outerHeight(); 
		var eleTopo = $('.economy').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".economy").css("animation", "scaleX 2s 1")
			$(".economy").css("-webkit-animation-fill-mode", "forwards")
		}
	})
</script>