<?php include("navbar.phtml") ?>


<br><br>

<section class="section">
	<div class="p-4 rounded-3 m-auto bg-light" style="width: 90%">

		<h1 class="text-center">
			Valoração
		</h1>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum elementum ante commodo tellus vestibulum viverra. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
		</p>

			<div class="row text-center">
				<div class="col">
					<button class="btn btn-success btn-ger-depart"> Configurar Médias</button>
				</div>
			</div>
			<br>

		<div class="bg-gray p-4 rounded-3">
			<h4>Ambiental 25%</h4>
			<div class="bg-white p-4 rounded-3" style="overflow-x: scroll; overflow-y: scroll">
				<br>
				<table class="text-center m-auto table-amb" style="color: black; width: 90%; opacity: 0">
					<tr class="tr-3">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>Mês</b>
						</td>
						<td>jan/19</td>
						<td>fev/19</td>
						<td>mar/19</td>
						<td>abr/19</td>
						<td>jun/19</td>
						<td>...</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>Total</b>
						</td>
					</tr>
					<tr class="bg-light">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>FP</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
					<tr class="tr-3">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>P</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
					<tr class="bg-light">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>Total</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
				</table>
				</div>
				<br>
				<h4>Social 25%</h4>
			<div class="bg-white p-4 rounded-3" style="overflow-x: scroll; overflow-y: scroll">
				<br>
				<table class="text-center m-auto table-soc" style="color: black; width: 90%; opacity: 0">
					<tr class="tr-3">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>Mês</b>
						</td>
						<td>jan/19</td>
						<td>fev/19</td>
						<td>mar/19</td>
						<td>abr/19</td>
						<td>jun/19</td>
						<td>...</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>Total</b>
						</td>
					</tr>
					<tr class="bg-light">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>FP</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
					<tr class="tr-3">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>P</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
					<tr class="bg-light">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>Total</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
				</table>
				</div>
				<br>
				<h4>Política 25%</h4>
			<div class="bg-white p-4 rounded-3" style="overflow-x: scroll; overflow-y: scroll">
				<br>
				<table class="text-center m-auto table-pol" style="color: black; width: 90%; opacity: 0">
					<tr class="tr-3">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>Mês</b>
						</td>
						<td>jan/19</td>
						<td>fev/19</td>
						<td>mar/19</td>
						<td>abr/19</td>
						<td>jun/19</td>
						<td>...</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>Total</b>
						</td>
					</tr>
					<tr class="bg-light">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>FP</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
					<tr class="tr-3">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>P</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
					<tr class="bg-light">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>Total</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
				</table>
				</div>
				<br>
				<h4>Técnica-Econômica 25%</h4>
			<div class="bg-white p-4 rounded-3" style="overflow-x: scroll; overflow-y: scroll">
				<br>
				<table class="text-center m-auto table-tec" style="color: black; width: 90%; opacity: 0">
					<tr class="tr-3">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>Mês</b>
						</td>
						<td>jan/19</td>
						<td>fev/19</td>
						<td>mar/19</td>
						<td>abr/19</td>
						<td>jun/19</td>
						<td>...</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>Total</b>
						</td>
					</tr>
					<tr class="bg-light">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>FP</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
					<tr class="tr-3">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>P</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
					<tr class="bg-light">
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>Total</b>
						</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td>00.000,00 KWh</td>
						<td class="bg-gray" style="border-bottom: 1px solid white">
							<b>00.000,00 KWh</b>
						</td>
					</tr>
				</table>
				</div>
				<br>
				<h4>Total Recursos</h4>
				<div class="bg-white p-4 rounded-3">
				<br>
				<img src="img/img.png" class="graf-total-rec w-50" style="margin-left: 20%; opacity: 0">
				</div>
				
		</div>
	
	</div>
</section>

<div class="container-black container-ger-depart fixed-top w-100 h-100 d-none">
	<div class="div-modal custom-input bg-white w-75 m-auto text-center rounded-3 mt-4 p-2">
		<i class="fa-solid fa-xmark" style="font-size: 30px; cursor: pointer; margin-left: 90%; margin-top: 20px"></i>
		<br>
		<form class=" w-75 m-auto rounded-3 p-3 text-center" style="border: 1px solid lightgray">
			<p class="text-green text-center"><b>Funções de média</b></p>
			<hr>
			
			Nome:
			<select>
				<option>Divisão Igual</option>
				<option>Unidade</option>
				<option>Área Técnica</option>
				<option>Planejamento e Operações</option>
			</select>
			<br><br>
			<div class="m-auto text-center">
				<button class="btn btn-green btn-div-add-mes">Salvar</button>
			</div>
			<br>
		</form>
		<br><br>
	</div>	
</div>

<script>
	$(window).on("scroll load",function(){
		var aparecer = 50; 
		var eleHeight = $('.graf-total-rec').outerHeight(); 
		var eleTopo = $('.graf-total-rec').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".graf-total-rec").css("animation", "panoramaRight 3s 1")
			$(".graf-total-rec").css("-webkit-animation-fill-mode", "forwards")
		}
	})

	$(window).on("scroll load1",function(){
		var aparecer = 50; 
		var eleHeight = $('.table-amb').outerHeight(); 
		var eleTopo = $('.table-amb').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".table-amb").css("animation", "scaleY 2s 1")
			$(".table-amb").css("-webkit-animation-fill-mode", "forwards")
		}
	})

	$(window).on("scroll load2",function(){
		var aparecer = 50; 
		var eleHeight = $('.table-soc').outerHeight(); 
		var eleTopo = $('.table-soc').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".table-soc").css("animation", "scaleY 2s 1")
			$(".table-soc").css("-webkit-animation-fill-mode", "forwards")
		}
	})

	$(window).on("scroll load3",function(){
		var aparecer = 50; 
		var eleHeight = $('.table-pol').outerHeight(); 
		var eleTopo = $('.table-pol').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".table-pol").css("animation", "scaleY 2s 1")
			$(".table-pol").css("-webkit-animation-fill-mode", "forwards")
		}
	})

	$(window).on("scroll load4",function(){
		var aparecer = 50; 
		var eleHeight = $('.table-tec').outerHeight(); 
		var eleTopo = $('.table-tec').offset().top; 
		var scrlTopo = $(window).scrollTop(); 
		var distance = eleTopo-scrlTopo; 
		var altJanela = window.innerHeight; 
		if(distance <= altJanela-(eleHeight*(aparecer/100))) {
			$(".table-tec").css("animation", "scaleY 2s 1")
			$(".table-tec").css("-webkit-animation-fill-mode", "forwards")
		}
	})
</script>